/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2024.2.0.3.0
    Soft IP Version: 1.4.0
    2025 03 28 08:16:44
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module image_bram (rd_clk_i, rd_en_i, rd_clk_en_i, rd_addr_i, rd_data_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  rd_clk_i;
    input  rd_en_i;
    input  rd_clk_en_i;
    input  [10:0]  rd_addr_i;
    output  [7:0]  rd_data_o;
endmodule